In [1]:
from random import randint, choice

# Map Reduce

In the part of the assignment you are requested to use Map Reduce paradigm to solve the following exercises.

**NOTE THAT**: **A solution that does not use map reduce is not valid!**

# Exercise 1

You have a list of dictionaries, each representing a student with the following properties: a name and an array of test scores. Your task is to use map, filter, and reduce to calculate the average test score for each student, and then return a list of dictionaries containing only the students whose average score is above 90.

In [3]:
students = [
    {"name": "Alice", "scores": [95, 92, 88, 100]},
    {"name": "Bob", "scores": [78, 81, 85, 80]},
    {"name": "Charlie", "scores": [99, 91, 94, 96]},
    {"name": "Diana", "scores": [85, 87, 89, 83]}
]

Use `map`, `reduce` and `filter` that produce an output like:

In [4]:
[
    {"name": "Alice", "average_score": 93.75},
    {"name": "Charlie", "average_score": 95.0}
]

[{'name': 'Alice', 'average_score': 93.75},
 {'name': 'Charlie', 'average_score': 95.0}]

### Test
Test your solution using the dataset generated by the following function.

In [5]:
def generate_random_student_dataset(num_students=50):
    names = [f"Student {i}" for i in range(1, num_students + 1)]
    dataset = [
        {
            "name": name,
            "scores": [randint(50, 100) for _ in range(randint(3, 6))]  # Random scores between 50 and 100
        }
        for name in names
    ]
    return dataset

random_student_dataset = generate_random_student_dataset(50)
random_student_dataset[:3]

[{'name': 'Student 1', 'scores': [64, 91, 100, 76, 66]},
 {'name': 'Student 2', 'scores': [95, 94, 61]},
 {'name': 'Student 3', 'scores': [90, 88, 97, 67, 98]}]

In [7]:
# your code goes here
from functools import reduce

students = [
    {'name': 'Student 1', 'scores': [64, 91, 100, 76, 66]},
    {'name': 'Student 2', 'scores': [95, 94, 61]},
    {'name': 'Student 3', 'scores': [90, 88, 97, 67, 98]}
]

result = list(filter(lambda s: s["average_score"] > 90, 
    map(lambda s: {"name": s["name"], "average_score": sum(s["scores"]) / len(s["scores"])}, students)))

print(result)

[]

## Exercise 2

You have a list of dictionaries, each representing a product with the following properties: name, price, and category. Using the functions `map`, `filter`, and `reduce`, calculate the average price of the products in each category and return a list of dictionaries containing only the categories where the average price exceeds 50.

Example input:

In [8]:
products = [
    {"name": "Product A", "price": 60, "category": "Electronics"},
    {"name": "Product B", "price": 40, "category": "Electronics"},
    {"name": "Product C", "price": 70, "category": "Home"},
    {"name": "Product D", "price": 30, "category": "Home"},
    {"name": "Product E", "price": 90, "category": "Sports"}
]

Use `map`, `reduce` and `filter` that produce an output like:

In [9]:
[
    {"category": "Electronics", "average_price": 50.0},
    {"category": "Sports", "average_price": 90.0}
]

[{'category': 'Electronics', 'average_price': 50.0},
 {'category': 'Sports', 'average_price': 90.0}]

### Test
Test your solution using the dataset generated by the following function.

In [10]:
def generate_random_product_dataset(num_products=100):
    categories = ["Electronics", "Home", "Sports", "Books", "Clothing", "Toys"]
    dataset = [
        {
            "name": f"Product {i}",
            "price": randint(10, 200),  # Random price between 10 and 200
            "category": choice(categories),  # Randomly choose a category
        }
        for i in range(1, num_products + 1)
    ]
    return dataset

# Example of using the function
random_dataset = generate_random_product_dataset(100)
random_dataset[:5]  # Display the first 5 entries to check the dataset structure

[{'name': 'Product 1', 'price': 183, 'category': 'Clothing'},
 {'name': 'Product 2', 'price': 194, 'category': 'Toys'},
 {'name': 'Product 3', 'price': 151, 'category': 'Books'},
 {'name': 'Product 4', 'price': 39, 'category': 'Books'},
 {'name': 'Product 5', 'price': 172, 'category': 'Clothing'}]

In [16]:
# your code goes here
# hints: 1) Group products by category (you don't need to use map reduce for this part), then 2) use map reduce paradigm to
# calculate the average price for each category and filter categories with an average price > 50

products = [
    {'name': 'Product 1', 'price': 183, 'category': 'Clothing'},
    {'name': 'Product 2', 'price': 194, 'category': 'Toys'},
    {'name': 'Product 3', 'price': 151, 'category': 'Books'},
    {'name': 'Product 4', 'price': 39, 'category': 'Books'},
    {'name': 'Product 5', 'price': 172, 'category': 'Clothing'}
]

categories = {category: [p["price"] for p in products if p["category"] == category] for category in set(p["category"] for p in products)}

result = list(filter(lambda c: c["average_price"] > 50,
    map(lambda category: {"category": category, "average_price": sum(categories[category]) / len(categories[category])}, categories)))

print(result)

[{'category': 'Clothing', 'average_price': 177.5}, {'category': 'Books', 'average_price': 95.0}, {'category': 'Toys', 'average_price': 194.0}]

# Exercise 3

You have a list of dictionaries, each representing an employee with the following properties: name, salary, and department. Your task is to use `map`, `filter`, and `reduce` to calculate the average salary for each department and return a list of dictionaries containing only the departments where the average salary is above 65,000.

**Example Input**

In [18]:
employees = [
    {"name": "John", "salary": 70000, "department": "Engineering"},
    {"name": "Jane", "salary": 75000, "department": "Engineering"},
    {"name": "Alice", "salary": 60000, "department": "HR"},
    {"name": "Bob", "salary": 68000, "department": "HR"},
    {"name": "Charlie", "salary": 90000, "department": "Marketing"},
    {"name": "Diana", "salary": 50000, "department": "Marketing"}
]

Use `map`, `reduce` and `filter` that produce an output like:

In [19]:
[
    {"department": "Engineering", "average_salary": 72500.0},
    {"department": "Marketing", "average_salary": 70000.0}
]

[{'department': 'Engineering', 'average_salary': 72500.0},
 {'department': 'Marketing', 'average_salary': 70000.0}]

### Test

Test your solution using the dataset generated by the following function.

In [20]:
def generate_random_employee_dataset(num_employees=50):
    departments = ["Engineering", "HR", "Marketing", "Sales", "Finance", "IT"]
    dataset = [
        {
            "name": f"Employee {i}",
            "salary": randint(40000, 120000),  # Random salary between 40,000 and 120,000
            "department": choice(departments)  # Randomly choose a department
        }
        for i in range(1, num_employees + 1)
    ]
    return dataset

random_employee_dataset = generate_random_employee_dataset(50)

random_employee_dataset[:3]  # Display the first 3 entries of each dataset for checking

[{'name': 'Employee 1', 'salary': 74083, 'department': 'Marketing'},
 {'name': 'Employee 2', 'salary': 45830, 'department': 'Marketing'},
 {'name': 'Employee 3', 'salary': 62323, 'department': 'Engineering'}]

In [21]:
# your code goes here
# hints: 1) Group employees' salaries by department (you don't need to use map reduce for this part), then 2) use map reduce paradigm to
# calculate the average salary for each department and filter departments with an average salary > threshold


employees = [
    {'name': 'Employee 1', 'salary': 74083, 'department': 'Marketing'},
    {'name': 'Employee 2', 'salary': 45830, 'department': 'Marketing'},
    {'name': 'Employee 3', 'salary': 62323, 'department': 'Engineering'}
]

departments = {dept: [e["salary"] for e in employees if e["department"] == dept] for dept in set(e["department"] for e in employees)}

result = list(filter(lambda d: d["average_salary"] > 65000,map(lambda dept: {"department": dept, "average_salary": sum(departments[dept]) / len(departments[dept])},departments)))

print(result)

[]

# Biopython

Write the following five functions to analyze global alignments between two sequences using Biopython's `pairwise2` module:

1. **countMatches(s1, s2)**  
   This function takes two sequences (`s1`, `s2`) aligned using global alignment (pairwise2.globalxx) of the same length. It returns the number of positions where the elements of both sequences match.

2. **countMismatches(s1, s2)**  
   This function takes two sequences (`s1`, `s2`) aligned using global alignment of the same length. It returns the number of positions where the elements of the two sequences are different (i.e., they are not gaps, and the characters do not match).

3. **countGapOpens(s1, s2)**  
   This function takes two sequences (`s1`, `s2`) aligned using global alignment of the same length. It returns the number of gap openings in the alignment (a gap is opened when a '-' appears in the sequence).

4. **countGapExtensions(s1, s2)**  
   This function takes two sequences (`s1`, `s2`) aligned using global alignment of the same length. It returns the number of gap extensions (where '-' continues in the alignment after an initial gap is opened).

5. **getScore(s1, s2, matchScore, mismatchPenalty, gapOpenPenalty, gapExtensionPenalty)**  
   This function takes two sequences (`s1`, `s2`) aligned using global alignment and returns the alignment score based on the provided scoring scheme: `matchScore` for matches, `mismatchPenalty` for mismatches, `gapOpenPenalty` for opening a gap, and `gapExtensionPenalty` for extending a gap.

In [22]:
# Add your functions here
from Bio.Align import PairwiseAligner

def countMatches(s1, s2):
    aligner = PairwiseAligner()
    aligner.mode = 'global'
    alignment = aligner.align(s1, s2)[0]
    align1, align2 = alignment.aligned
    matches = 0
    for (start1, end1), (start2, end2) in zip(align1, align2):
        matches += end1 - start1
    return matches

def countMismatches(s1, s2):
    aligner = PairwiseAligner()
    aligner.mode = 'global'
    alignment = aligner.align(s1, s2)[0]
    align1, align2 = alignment.aligned
    mismatches = 0
    for (start1, end1), (start2, end2) in zip(align1, align2):
        mismatches += (end1 - start1) - sum(a == b for a, b in zip(s1[start1:end1], s2[start2:end2]))
    return mismatches

def countGapOpens(s1, s2):
    aligner = PairwiseAligner()
    aligner.mode = 'global'
    alignment = aligner.align(s1, s2)[0]
    seq1, seq2 = alignment.target, alignment.query
    gap_opens = sum((seq1[i] == '-' or seq2[i] == '-') and (seq1[i - 1] != '-' and seq2[i - 1] != '-') for i in range(1, len(seq1)))
    return gap_opens

def countGapExtensions(s1, s2):
    aligner = PairwiseAligner()
    aligner.mode = 'global'
    alignment = aligner.align(s1, s2)[0]
    seq1, seq2 = alignment.target, alignment.query
    gap_extensions = sum((seq1[i] == '-' or seq2[i] == '-') and (seq1[i - 1] == '-' or seq2[i - 1] == '-') for i in range(1, len(seq1)))
    return gap_extensions

def getScore(s1, s2, matchScore, mismatchPenalty, gapOpenPenalty, gapExtensionPenalty):
    aligner = PairwiseAligner()
    aligner.mode = 'global'
    aligner.match_score = matchScore
    aligner.mismatch_score = -mismatchPenalty
    aligner.open_gap_score = -gapOpenPenalty
    aligner.extend_gap_score = -gapExtensionPenalty
    alignment = aligner.align

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(

### Test
Align the sequences of the [Interleukin-12](https://en.wikipedia.org/wiki/Interleukin_12) chain A (denoted as `s1`) from the file [`IL12A.fasta`](https://qcbsciprolab2020.readthedocs.io/en/latest/file_samples/IL12A.fasta) and the Interleukin-12 chain B (denoted as `s2`) from the file [`IL12B.fasta`](https://qcbsciprolab2020.readthedocs.io/en/latest/file_samples/IL12B.fasta) and check the score as computed from pairwise2 and from your functions.

In [ ]:
# add the output of the test here